#ifndef SCS_5_DEFAULTS_H_
#define SCS_5_DEFAULTS_H_ 1

/* ============================================================================================== */

#include <limits.h>

/* ---------------------------------------------------------------------------------------------- */

#define SCS_DEFAULT_LOGGER_LOGLEVEL							SCS_LOGLEVEL_NOTICE

#define SCS_DEFAULT_CALLBACK_MAXENTRIES						16		// callbacks

#define SCS_DEFAULT_SEND_QUEUESIZE							128		// sockets
#define SCS_DEFAULT_CLOSE_QUEUESIZE							128		// sockets

#define SCS_DEFAULT_SOCKET_OPTION							(SCS_SKTOPTN_VERIFY | SCS_SKTOPTN_RTTM | SCS_SKTOPTN_PMTUM)

#define SCS_DEFAULT_SOCKET_CONNECT_TIMEOUT					10		// sec
#define SCS_DEFAULT_SOCKET_CONNECT_REDUNDANCY_TIMES			SCS_REDUNDANCY_MAXTIMES
#define SCS_DEFAULT_SOCKET_CONNECT_REDUNDANCY_FUNCTION		SCSConnectionCallbackFunction

#define SCS_DEFAULT_SOCKET_SEND_TIMEOUT						0		// msec
#define SCS_DEFAULT_SOCKET_SEND_REDUNDANCY_TIMES			0		// sec
#define SCS_DEFAULT_SOCKET_SEND_REDUNDANCY_FUNCTION			NULL
#define SCS_DEFAULT_SOCKET_SEND_QUEUELENGTH					10000	// packets

#define SCS_DEFAULT_SOCKET_CLOSE_REDUNDANCY_TIMES			3
#define SCS_DEFAULT_SOCKET_CLOSE_REDUNDANCY_FUNCTION		SCSCloseCallbackFunction
#define SCS_DEFAULT_SOCKET_CLOSE_DELAYTIME					30		// sec

#define SCS_DEFAULT_SOCKET_RECEIVE_TIMEOUT					0		// sec
#define SCS_DEFAULT_SOCKET_RECEIVE_QUEUELENGTH				10000	// packets

#define SCS_DEFAULT_SOCKET_NOTIFICATION_TIMEOUT				30		// sec
#define SCS_DEFAULT_SOCKET_NOTIFICATION_INTERVAL			500		// msec

#define SCS_DEFAULT_SOCKET_VERIFICATION_ENABLED				true
#define SCS_DEFAULT_SOCKET_VERIFICATION_METHOD				SCS_PKTVRFMETHOD_CRC16

#define SCS_DEFAULT_SOCKET_PMTUDISCOVERY_ENABLED			true
#define SCS_DEFAULT_SOCKET_PMTUDISCOVERY_INTERVALSECONDS	1
#define SCS_DEFAULT_SOCKET_PMTUDISCOVERY_INTERVALPACKETS	0
#define SCS_DEFAULT_SOCKET_PMTUDISCOVERY_INTERVALBYTES		0

#define SCS_DEFAULT_SOCKET_RTTMEASUREMENT_ENABLED			true
#define SCS_DEFAULT_SOCKET_RTTMEASUREMENT_MAXPACKETS		16		// packets

#define SCS_DEFAULT_SOCKET_PLRMEASUREMENT_ENABLED			true
#define SCS_DEFAULT_SOCKET_PLRMEASUREMENT_SAMPLES			128

#define SCS_DEFAULT_SOCKET_JITTERMEASUREMENT_ENABLED		true
#define SCS_DEFAULT_SOCKET_JITTERMEASUREMENT_SAMPLES		256

#define SCS_DEFAULT_SOCKET_MTUSIZE							1500	// bytes

/* ============================================================================================== */

#endif /* SCS_5_DEFAULTS_H_ */
